Algoritmo "funcionário"

// ler o nome de um funcinário []
// ler o valor da hora trabalhada []
// ler a quantidade de hotas trabalhadas []

Var

 nome : caractere
 valorHora, qtdHora, salario : real
 
Inicio
.
 escreva("Nome: ")
 leia(nome)
 
 escreva("Valor hora: ")
 leia(valorHora)
 escreva("Quantidade hora: ")
 leia(qtdHora)
 
 salario <-   qtdHora * valorHora

 escreval("Salário = R$", salario:8:2)
 
Fimalgoritmo