Algoritmo "soma"

// ler os valores de X e Y []
// exibir a soma entre esses dois valores []

Var
 // declaração de variáveis com nome e tipo
 x, y, soma : inteiro

Inicio

 // entrada de dados
 escreva("insira o valor de X: ")
 leia(x)
 
 escreva("insira o valor de y: ")
 leia(y)
 
 //processamento
 soma <- x + y
 
 //saída de dados
 escreva("Soma de X e Y = ", soma)

Fimalgoritmo